### ISSUE TITLE
please check licecenses

### ISSUE THREAD

**Issue by danmarsden** [Oomaxpro/moodle-auth_cognito#10]
The header of this file states "GPL" as it's a moodle file, but then in your php comment you state MIT:

https://github.com/Oomaxpro/moodle-auth_cognito/blob/oomaxpro/classes/helper/FileTool.php#L23

It's fine to include MIT code inside your plugin, (they must be defined in the thirdpartyllibs.xml file as well) but I think in this case it's a typo and that @license line referred to above can be deleted. (please check all your other files for this as well.)

**Comment by SwayzeD** [comment]
Great catch, thanks!

**Comment by SwayzeD** [comment]
This line has been deleted and a ticket has been raised to review all others.
