### ISSUE TITLE
once a token is available, the end user can enrol in any course they want.

### ISSUE THREAD

**Issue by danmarsden** [Oomaxpro/moodle-auth_cognito#12]
https://github.com/Oomaxpro/moodle-auth_cognito/blob/oomaxpro/index.php#L40

it looks like when a user obtains a token - they can then pass a courses array to the script and triggeer a manual enrolment into any course they want - I haven't had a good look at the workflow here, but if this happens within the browser session it looks like it presents a security risk.

**Comment by danmarsden** [comment]
same thing with groups and cohorts.

**Comment by SwayzeD** [comment]
This has now been resolved
