### ISSUE TITLE
Camel case in classes and methods names

### ISSUE THREAD

**Issue by volodymyrdovhan** [Oomaxpro/moodle-auth_cognito#45]
Hello,
based on Moodle coding styles, all classes, methods/functions, and variables should be snake-cased in lowercase English:
https://moodledev.io/general/development/policies/codingstyle#naming-conventions

![image](https://github.com/user-attachments/assets/8cb66c32-7f9b-4fdc-8522-7d4c922b2329)

![image](https://github.com/user-attachments/assets/0987c309-846d-4fee-8900-9ea1340ecfc9)

**Comment by volodymyrdovhan** [comment]
The issue still exists in custom classes:
![image](https://github.com/user-attachments/assets/2e13378d-d84e-467c-82e8-9d919fc04edb)

**Comment by dustinbrisebois** [comment]
this is resolved in latest release
