### ISSUE TITLE
Injecting autoloader file in the language file

### ISSUE THREAD

**Issue by volodymyrdovhan** [Oomaxpro/moodle-auth_cognito#47]
Hello,
I found injecting additional files into the language file. This is prohibited, as language files is used in language customisation panel and other Moodle features.
https://moodledev.io/general/community/plugincontribution/checklist#strings

![image](https://github.com/user-attachments/assets/6bb969f5-1d65-47b1-b948-0d5288555e07)

**Comment by dustinbrisebois** [comment]
@volodymyrdovhan  this is related to an old version of the plugin.
