### ISSUE TITLE
Missed thirdpartylibs.xml

### ISSUE THREAD

**Issue by volodymyrdovhan** [Oomaxpro/moodle-auth_cognito#48]
Hello,
all third-party libraries should be described in thirdpartylibs.xml file:
https://moodledev.io/general/community/plugincontribution/thirdpartylibraries

![image](https://github.com/user-attachments/assets/e26cca3f-c235-4d79-9d31-a95c8df9405e)

**Comment by SwayzeD** [comment]
Hello @volodymyrdovhan , Please review the production branch called "oomaxpro"

https://github.com/Oomaxpro/moodle-auth_cognito/blob/oomaxpro/thirdpartylibs.xml

This is the current file.

Thank you!
