### ISSUE TITLE
Missed correct header and copyrights notes

### ISSUE THREAD

**Issue by volodymyrdovhan** [Oomaxpro/moodle-auth_cognito#50]
Hello,
in most files missed the correct header and copyrights/author notes:
https://moodledev.io/general/community/plugincontribution/checklist#boilerplate
https://moodledev.io/general/community/plugincontribution/checklist#copyrights

![image](https://github.com/user-attachments/assets/af551b57-d733-4efe-af80-702c990c474a)

**Comment by dustinbrisebois** [comment]
@volodymyrdovhan this is related to an old release of the plugin

**Comment by volodymyrdovhan** [comment]
Hello @dustinbrisebois 
I reviewed the version uploaded to the Moodle Plugins library.
Please upload the newest version to the library and leave a comment, I will review it.

Thanks
Vlad
