### ISSUE TITLE
Global $USER overrite

### ISSUE THREAD

**Issue by volodymyrdovhan** [Oomaxpro/moodle-auth_cognito#51]
Hello,
the global $USER should not be overridden by the plugin. 
Moodle will automatically handle this with complete_user_login();

![image](https://github.com/user-attachments/assets/ccd375c4-6876-4a85-812c-9fee5a30d8e3)

**Comment by dustinbrisebois** [comment]
@volodymyrdovhan this is related to an old release of the plugin
