### ISSUE TITLE
Missed Privacy API implementation

### ISSUE THREAD

**Issue by volodymyrdovhan** [Oomaxpro/moodle-auth_cognito#52]
Hello,

Each Moodle plugin is required to implement the Privacy API. 

For further details, please refer to the documentation:
[Privacy API Checklist](https://moodledev.io/general/community/plugincontribution/checklist#privacy)
[Moodle Privacy API Documentation](https://moodledev.io/docs/4.5/apis/subsystems/privacy)

Thank you.

**Comment by dustinbrisebois** [comment]
resolved in latest build
