### ISSUE TITLE
MIT License notes

### ISSUE THREAD

**Issue by volodymyrdovhan** [Oomaxpro/moodle-auth_cognito#53]
Hello,
Some files declare an MIT license. Since Moodle is distributed under the GNU General Public License (GPL), the plugin must also use a GPL-compatible license.
https://moodledev.io/general/community/plugincontribution/checklist#licensing

![image](https://github.com/user-attachments/assets/43b808af-9623-4041-9f83-b7a2ca8ae202)
![image](https://github.com/user-attachments/assets/af465267-fa82-4c29-9a1e-8f22cead9d05)

**Comment by dustinbrisebois** [comment]
@volodymyrdovhan  this is related to an old version of the plugin.

**Comment by SwayzeD** [comment]
@volodymyrdovhan Thank you for reviewing! 

Are you using our production  "oomaxpro" branch for the review?

**Comment by volodymyrdovhan** [comment]
Hello @SwayzeD , I reviewed the version uploaded to the Moodle Plugins library.
Please upload the newest version to the library and leave a comment, I will review it.

Thanks
Vlad
