### ISSUE TITLE
Not used external services declaration

### ISSUE THREAD

**Issue by volodymyrdovhan** [Oomaxpro/moodle-auth_cognito#57]
Hello,
seams declared in services.php services are not using anywhere. Please remove this file if not needed.

https://github.com/Oomaxpro/moodle-auth_cognito/blob/e266fadc33e0863e4388bb4880d80fa8fa515429/db/services.php

![image](https://github.com/user-attachments/assets/317610c4-1b86-4309-93fe-ccb7b18c451a)

**Comment by dustinbrisebois** [comment]
resolved in latest build
