### ISSUE TITLE
curl_init() usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [Oomaxpro/moodle-auth_cognito#61]
Hello,
there is a curl() class wrapper in Moodle which is recommended for usage.
Could you please replace curl_init() with moodle curn() class.

You can find this class in lib/filelib.php.

![image](https://github.com/user-attachments/assets/2f5014fb-a217-4869-8c83-dffa4f49721d)

**Comment by dustinbrisebois** [comment]
resolved in latest build
